### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by ghost** [benzBrake/Docker-TiebaSign#2]
错误代码arm32
```
Traceback (most recent call last):
  File "/tiebaSign.py", line 90, in <module>
    schedule.run_pending()
  File "/usr/lib/python3.8/site-packages/schedule/__init__.py", line 592, in run_pending
    default_scheduler.run_pending()
  File "/usr/lib/python3.8/site-packages/schedule/__init__.py", line 94, in run_pending
    self._run_job(job)
  File "/usr/lib/python3.8/site-packages/schedule/__init__.py", line 147, in _run_job
    ret = job.run()
  File "/usr/lib/python3.8/site-packages/schedule/__init__.py", line 491, in run
    ret = self.job_func()
  File "/tiebaSign.py", line 76, in app
    tb = tieba()
  File "/tiebaSign.py", line 25, in __init__
    self.get_list()
  File "/tiebaSign.py", line 34, in get_list
    rul = re.findall(r'forumArr":(\[.+?), "ihome"', r.text)[0]
IndexError: list index out of range

```

**Comment by benzBrake** [comment]
这个脚本不是我开发的，不能用我也没办法，我不会python
